"""Publish a kb_feed workbook to Pinecone — the NLQ agent's knowledge base.

    kb_feed*.xlsx ─► STEP 1  read every non-empty sheet; validate actions, keys, dates, JSON
                     STEP 2  resolve: latest effective_date per record key wins; DELETE removes
                     STEP 3  build records: id, namespace, embed_text, metadata, content_hash
                     STEP 4  diff: fetch each record's stored content_hash from Pinecone
                     STEP 5  embed what changed (Bedrock Titan v2, 1024-d, normalised) and upsert
                     STEP 6  delete: DELETE rows, and — in --mode full — vectors no longer in the feed
                     STEP 7  verify: vector count per namespace, self-retrieval, canary questions

    One index, one namespace per collection:
        nlq-schema    nlq_table · nlq_column · nlq_join
        nlq-examples  nlq_examples         (embeds the question + paraphrases; the SQL rides in metadata)
        nlc-examples  nlc_examples
        common        glossary · capability_card

    cd ingestion
    python pinecone_kb/kb_to_pinecone.py data/kb_feed_ecom.xlsx --index ecom-kb
    python pinecone_kb/kb_to_pinecone.py data/changes_2026-11-01.xlsx --index ecom-kb --mode incremental
    python pinecone_kb/kb_to_pinecone.py data/kb_feed_ecom.xlsx --dry-run      (no Pinecone, no Bedrock)

ADAPTED FROM THE ACT OPENSEARCH PIPELINE (nb0-nb2), WHAT CHANGED AND WHY
    - No S3 staging and no gold Delta table: one workbook of a few hundred rows,
      and Pinecone metadata carries each record's content_hash, so Pinecone
      itself is the publish state that kb_published_state used to be.
    - Namespaces instead of five indexes: Pinecone's built-in partition.
    - cosine instead of faiss innerproduct: Pinecone supports cosine natively;
      Titan still embeds with normalize=True, so the scores read the same.
    - embed_exempt rows are NOT stored: every Pinecone record needs a vector.
      They are counted and reported; in the e-commerce feed they are the 8
      latitude/longitude columns, which no analyst searches for.
    - glossary and capability_card get builders: the reference README calls
      them wired, its code has none.
    - enum_values split on "|" (the feed's separator), not ";" — the reference
      stored "Cancelled | Delivered | …" as ONE list item.

MODES
    full         (default) the workbooks hold the COMPLETE knowledge base; any
                 vector in a namespace this run owns that is not in the feed is deleted.
    incremental  the workbooks hold CHANGES only: INSERT/UPDATE upsert, DELETE
                 removes, nothing else is touched.

WHAT THIS DOES NOT DO
    - It never touches a namespace whose sheets were empty in this run.
    - It does not embed the SQL or Cypher of an example, only its question and
      paraphrases — the agent matches language, then reads the vetted query.
    - It does not decide `verified`: examples keep the workbook's flag, and an
      agent should filter on verified = True.
"""
import argparse
import ast
import hashlib
import json
import os
import re
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime

MODEL_ID = "amazon.titan-embed-text-v2:0"
DIMENSION = 1024
METADATA_LIMIT = 38_000            # Pinecone caps metadata at 40 KB per record
BATCH = 100

# sheet -> (namespace, record key columns, record type stored in metadata)
SHEETS = {
    "nlq_table":       ("nlq-schema",   ["table"],                              "table"),
    "nlq_column":      ("nlq-schema",   ["table", "column"],                    "column"),
    "nlq_join":        ("nlq-schema",   ["left_table", "right_table", "join_on"], "join"),
    "nlq_examples":    ("nlq-examples", ["question"],                           "example"),
    "nlc_examples":    ("nlc-examples", ["question"],                           "example"),
    "glossary":        ("common",       ["term"],                               "glossary"),
    "capability_card": ("common",       ["description"],                        "capability_card"),
}
CANARIES = {   # soft checks: a known question should surface a known record
    "nlq-schema": [("monthly revenue from orders", "ecom.orders"),
                   ("which carrier delivers on time", "ecom.shipments"),
                   ("products below reorder point", "ecom.inventory")],
    "nlq-examples": [("revenue generated by each coupon", "coupon")],
    "common": [("average order value", "Average Order Value")],
}


# ── cell helpers ─────────────────────────────────────────────────────────
def clean(v) -> str:
    s = "" if v is None else str(v).strip()
    return "" if s.lower() in ("nan", "none", "null") else s


def as_list(v, sep: str = ";") -> list[str]:
    return [x.strip() for x in clean(v).split(sep) if x.strip()]


def as_bool(v) -> bool:
    return clean(v).lower() in ("true", "1", "yes", "y")


def as_date(v) -> str:
    """YYYY-MM-DD. Also accepts DD-MM-YYYY text and Excel date cells."""
    if hasattr(v, "strftime"):
        return v.strftime("%Y-%m-%d")
    s = clean(v)[:10]
    for fmt in ("%Y-%m-%d", "%d-%m-%Y"):
        try:
            return datetime.strptime(s, fmt).strftime("%Y-%m-%d")
        except ValueError:
            pass
    raise ValueError(f"bad date {v!r}")


def as_map(v) -> dict | None:
    """value_map: strict JSON, tolerating what Excel inserts (from the reference's
    _coerce_map): non-breaking spaces, curly quotes, Python-dict style."""
    s = clean(v)
    if not s:
        return None
    s = (s.replace("\u00a0", " ").replace("\u201c", '"').replace("\u201d", '"')
          .replace("\u2018", "'").replace("\u2019", "'"))
    try:
        out = json.loads(s)
        out = json.loads(out) if isinstance(out, str) else out
        if isinstance(out, dict):
            return out
    except ValueError:
        pass
    out = ast.literal_eval(s)
    if isinstance(out, dict):
        return {str(k): out[k] for k in out}
    raise ValueError(f"value_map is not a JSON object: {s[:60]!r}")


def short_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


# ── STEP 1 + 2 — read, validate, resolve ─────────────────────────────────
def read_feed(paths: list[str]) -> dict[str, list[dict]]:
    """Rows per sheet across all workbooks, validated. A workbook later in the
    list wins a same-day tie: give files oldest first."""
    import openpyxl
    rows: dict[str, list[dict]] = {}
    errors = []
    for order, path in enumerate(paths):
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        for sheet in wb.sheetnames:
            if sheet == "Instructions":
                continue
            it = wb[sheet].iter_rows(values_only=True)
            header = [clean(h) for h in next(it, [])]
            data = [dict(zip(header, r)) for r in it if any(clean(x) for x in r)]
            if not data:
                continue
            if sheet not in SHEETS:
                errors.append(f"[{sheet}] has {len(data)} rows but no builder — add one to SHEETS; "
                              "refusing to drop it silently")
                continue
            _, key, _ = SHEETS[sheet]
            for n, r in enumerate(data, start=2):
                r["_file_order"], r["_row"] = order, n
                where = f"[{sheet}] {os.path.basename(path)} row {n}"
                if clean(r.get("action")).upper() not in ("INSERT", "UPDATE", "DELETE"):
                    errors.append(f"{where}: bad action {r.get('action')!r}")
                if any(not clean(r.get(k)) for k in key):
                    errors.append(f"{where}: empty key column in {key}")
                try:
                    r["effective_date"] = as_date(r.get("effective_date"))
                except ValueError as exc:
                    errors.append(f"{where}: {exc}")
                try:
                    as_map(r.get("value_map"))
                except (ValueError, SyntaxError) as exc:
                    errors.append(f"{where}: {exc}")
            rows.setdefault(sheet, []).extend(data)
    if errors:
        raise SystemExit("FEED VALIDATION FAILED — nothing was published:\n  " + "\n  ".join(errors[:50]))
    return rows


def resolve(sheet: str, rows: list[dict]) -> list[dict]:
    """Latest effective_date per key wins (ties: later file, then later row)."""
    _, key, _ = SHEETS[sheet]
    latest = {}
    for r in sorted(rows, key=lambda r: (r["effective_date"], r["_file_order"], r["_row"])):
        latest[tuple(clean(r[k]).lower() if k == "question" else clean(r[k]) for k in key)] = r
    return list(latest.values())


# ── STEP 3 — records ─────────────────────────────────────────────────────
@dataclass
class Record:
    id: str
    namespace: str
    action: str
    exempt: bool
    embed_text: str
    metadata: dict = field(default_factory=dict)

    @property
    def content_hash(self) -> str:
        """What 'changed' means: the embedded text, or for exempt rows the payload."""
        return short_hash(self.embed_text or json.dumps(self.metadata, sort_keys=True, default=str))


def slug(*parts: str) -> str:
    return re.sub(r"[^a-z0-9._-]+", "_", ".".join(parts).lower()).strip("_")[:400]


def build(sheet: str, r: dict) -> Record:
    ns, _, rtype = SHEETS[sheet]
    action = clean(r["action"]).upper()
    exempt = clean(r.get("embed_exempt")).upper() in ("Y", "TRUE")
    base = {"type": rtype, "sheet": sheet, "change_reason": clean(r.get("change_reason")),
            "effective_date": r["effective_date"]}
    syn, ans = as_list(r.get("analyst_synonyms")), as_list(r.get("answers_questions"))

    if sheet == "nlq_table":
        full = clean(r["table"])
        desc, grain = clean(r.get("description")), clean(r.get("grain"))
        text = f"{full} ({clean(r.get('table_type'))} table) — {desc}"
        text += (f" Grain: {grain}." if grain else "") + (f" Also called: {'; '.join(syn)}." if syn else "")
        text += f" Answers: {'; '.join(ans)}." if ans else ""
        meta = {**base, "table": full, "name": full.split(".")[-1], "description": desc, "grain": grain,
                "analyst_synonyms": syn, "table_type": clean(r.get("table_type")),
                "row_count": clean(r.get("row_count")), "source_systems": as_list(r.get("source_systems"))}
        rid = f"nlq_table:{slug(full)}"
    elif sheet == "nlq_column":
        full, col = clean(r["table"]), clean(r["column"])
        desc, dtype, vmap = clean(r.get("description")), clean(r.get("data_type")), as_map(r.get("value_map"))
        enums = as_list(r.get("enum_values"), sep="|")
        text = f"{full}.{col} ({dtype}) — {desc}" + (f" Also called: {'; '.join(syn)}." if syn else "")
        if vmap:
            text += " Values: " + ", ".join(f"{k}={v}" for k, v in list(vmap.items())[:60]) + "."
        elif enums:
            text += " Values: " + ", ".join(enums[:60]) + "."
        text += f" Answers: {'; '.join(ans)}." if ans else ""
        meta = {**base, "table": full, "column": col, "data_type": dtype, "description": desc,
                "analyst_synonyms": syn, "where_to_use": clean(r.get("where_to_use")),
                "is_enum": as_bool(r.get("is_enum")), "enum_values": enums,
                "is_date": as_bool(r.get("is_date")), "date_format": clean(r.get("date_format")),
                "value_map": json.dumps(vmap) if vmap else "", "sample_values": as_list(r.get("sample_values")),
                "main_investigative_target": clean(r.get("main_investigative_target")).upper() == "Y"}
        rid = f"nlq_column:{slug(full, col)}"
    elif sheet == "nlq_join":
        left, right, on = clean(r["left_table"]), clean(r["right_table"]), clean(r["join_on"])
        card, desc = clean(r.get("cardinality")), clean(r.get("description"))
        text = f"{left} JOIN {right} ON {on}" + (f" ({card})" if card else "") + f" — {desc}"
        meta = {**base, "left_table": left, "right_table": right, "join_on": on, "cardinality": card, "description": desc}
        rid = f"nlq_join:{slug(left, right, on)}"
    elif sheet in ("nlq_examples", "nlc_examples"):
        q, paras = clean(r["question"]), as_list(r.get("paraphrases"))
        text = q + (" | " + " | ".join(paras) if paras else "")
        meta = {**base, "question": q, "paraphrases": paras, "query": clean(r.get("query")),
                "pattern": clean(r.get("pattern")), "scenario": clean(r.get("fraud_scenario")),
                "entities": as_list(r.get("entities")), "verified": clean(r.get("verified")).upper() == "Y",
                "source": clean(r.get("source")), "owner": clean(r.get("owner")),
                "last_validated": clean(r.get("last_validated")), "dialect": clean(r.get("dialect")),
                "tables_used": as_list(r.get("tables_used"))}
        rid = f"{sheet[:3]}_example:{hashlib.sha1(q.lower().encode()).hexdigest()[:12]}"
    elif sheet == "glossary":
        term, cat, meaning = clean(r["term"]), clean(r.get("category")), clean(r.get("meaning"))
        syns, maps = as_list(r.get("synonyms")), as_list(r.get("maps_to"))
        text = f"{term} ({cat}) — {meaning}" + (f" Also called: {'; '.join(syns)}." if syns else "")
        text += f" Maps to: {'; '.join(maps)}." if maps else ""
        meta = {**base, "term": term, "category": cat, "meaning": meaning, "synonyms": syns, "maps_to": maps}
        rid = f"glossary:{slug(term)}"
    else:  # capability_card
        desc = clean(r["description"])
        text = desc
        meta = {**base, "source": clean(r.get("source")), "description": desc}
        rid = f"capability_card:{short_hash(desc)}"

    meta["text"] = text
    return Record(rid, ns, action, exempt, "" if exempt else text, meta)


def records_from(paths: list[str]) -> tuple[list[Record], set[str]]:
    """All resolved records, and the namespaces this run owns (non-empty sheets)."""
    rows = read_feed(paths)
    records = [build(sheet, r) for sheet, rs in rows.items() for r in resolve(sheet, rs)]
    ids = [r.id for r in records]
    if len(ids) != len(set(ids)):
        dup = sorted({i for i in ids if ids.count(i) > 1})[:5]
        raise SystemExit(f"two records map to the same id: {dup}")
    return records, {SHEETS[s][0] for s in rows}


def pinecone_metadata(rec: Record) -> dict:
    """Pinecone accepts string, number, boolean or list-of-string values — no
    nulls, no nested objects. Drop empties; refuse oversized metadata."""
    out = {}
    for k, v in {**rec.metadata, "content_hash": rec.content_hash}.items():
        if v in ("", None, []):
            continue
        out[k] = [str(x) for x in v] if isinstance(v, list) else v
    size = len(json.dumps(out).encode("utf-8"))
    if size > METADATA_LIMIT:
        raise SystemExit(f"{rec.id}: metadata is {size:,} bytes; Pinecone allows 40 KB")
    return out


# ── embedding (from the reference: Titan v2, normalised, retry with backoff) ──
def titan_embedder(region: str):
    import boto3
    client = boto3.client("bedrock-runtime", region_name=region)

    def embed(text: str, max_retries: int = 6) -> list[float]:
        body = json.dumps({"inputText": text[:45_000], "dimensions": DIMENSION, "normalize": True})
        delay = 1.0
        for attempt in range(max_retries):
            try:
                resp = client.invoke_model(modelId=MODEL_ID, contentType="application/json",
                                           accept="application/json", body=body)
                return json.loads(resp["body"].read())["embedding"]
            except Exception:
                if attempt == max_retries - 1:
                    raise
                time.sleep(delay)
                delay = min(delay * 2, 30)
        raise RuntimeError("unreachable")
    return embed


# ── STEP 4-6 — diff, embed, upsert, delete ───────────────────────────────
def stored_hashes(index, namespace: str, ids: list[str]) -> dict[str, str]:
    found = {}
    for i in range(0, len(ids), BATCH):
        resp = index.fetch(ids=ids[i:i + BATCH], namespace=namespace)
        for vid, vec in resp.vectors.items():
            found[vid] = (vec.metadata or {}).get("content_hash", "")
    return found


def all_ids(index, namespace: str) -> set[str]:
    return {item.id for page in index.list(namespace=namespace) for item in page.vectors}


def publish(index, embed, records: list[Record], owned: set[str], mode: str, full_reembed: bool) -> dict:
    stats = {"embedded": 0, "unchanged": 0, "exempt": 0, "deleted": 0, "first": None}
    for ns in sorted(owned):
        mine = [r for r in records if r.namespace == ns]
        live = [r for r in mine if r.action != "DELETE" and not r.exempt]
        stats["exempt"] += sum(1 for r in mine if r.action != "DELETE" and r.exempt)

        # STEP 4 — what Pinecone already holds for these ids
        have = stored_hashes(index, ns, [r.id for r in mine])
        todo = [r for r in live if full_reembed or have.get(r.id) != r.content_hash]
        stats["unchanged"] += len(live) - len(todo)

        # STEP 5 — embed and upsert only what changed
        batch = []
        for r in todo:
            vec = embed(r.embed_text)
            stats["first"] = stats["first"] or (r.id, ns, vec)
            batch.append({"id": r.id, "values": vec, "metadata": pinecone_metadata(r)})
            if len(batch) == BATCH:
                index.upsert(vectors=batch, namespace=ns)
                batch = []
        if batch:
            index.upsert(vectors=batch, namespace=ns)
        stats["embedded"] += len(todo)

        # STEP 6 — DELETE rows; exempt rows that were embedded before; and in
        #          full mode, every vector of this namespace not in the feed
        gone = {r.id for r in mine if (r.action == "DELETE" or r.exempt) and r.id in have}
        if mode == "full":
            gone |= all_ids(index, ns) - {r.id for r in live}
        for chunk in [sorted(gone)[i:i + 1000] for i in range(0, len(gone), 1000)]:
            index.delete(ids=chunk, namespace=ns)
        stats["deleted"] += len(gone)
        print(f"  {ns:13} live {len(live):>4} | embedded {len(todo):>4} | unchanged {len(live) - len(todo):>4} | deleted {len(gone):>3}")
    return stats


# ── STEP 7 — verify ──────────────────────────────────────────────────────
def verify(index, embed, records: list[Record], owned: set[str], first, wait_s: int = 90) -> bool:
    expected = {ns: sum(1 for r in records if r.namespace == ns and r.action != "DELETE" and not r.exempt) for ns in owned}
    deadline = time.time() + wait_s       # serverless indexes are eventually consistent
    while True:
        spaces = index.describe_index_stats().namespaces      # one snapshot per pass
        counts = {ns: (spaces[ns].vector_count if ns in spaces else 0) for ns in owned}
        if counts == expected or time.time() > deadline:
            break
        time.sleep(5)
    ok = counts == expected
    for ns in sorted(owned):
        print(f"  [{'OK' if counts[ns] == expected[ns] else 'MISMATCH'}] {ns}: {counts[ns]} vectors, feed has {expected[ns]}")
    if first:                               # the index returns a record for its own vector
        rid, ns, vec = first
        top = [m.id for m in index.query(vector=vec, top_k=3, namespace=ns).matches]
        print(f"  [{'OK' if rid in top else 'FAILED'}] self-retrieval of {rid}: top-3 {top}")
        ok &= rid in top
    for ns in sorted(owned):
        for question, expect in CANARIES.get(ns, []):
            hits = index.query(vector=embed(question), top_k=5, namespace=ns, include_metadata=True).matches
            found = any(expect.lower() in json.dumps(h.metadata or {}).lower() for h in hits)
            print(f"  canary {ns} [{question}] -> {'OK' if found else 'WEAK (review)'}")
    return ok


def open_index(pc, name: str, cloud: str, region: str):
    """Create the index if missing; refuse one with the wrong dimension or metric."""
    from pinecone import ServerlessSpec
    if not pc.has_index(name):
        print(f"creating index {name} ({DIMENSION}-d, cosine, {cloud}/{region})")
        pc.create_index(name=name, dimension=DIMENSION, metric="cosine", spec=ServerlessSpec(cloud=cloud, region=region))
        while not pc.describe_index(name).status["ready"]:
            time.sleep(3)
    desc = pc.describe_index(name)
    if desc.dimension != DIMENSION or str(desc.metric) != "cosine":
        raise SystemExit(f"index {name} is {desc.dimension}-d / {desc.metric}; this pipeline writes "
                         f"{DIMENSION}-d / cosine — use another index name")
    return pc.Index(host=desc.host)


def main() -> None:
    ap = argparse.ArgumentParser(description="Publish kb_feed workbooks to Pinecone")
    ap.add_argument("workbooks", nargs="+", help="kb_feed .xlsx files, oldest first")
    ap.add_argument("--index", help="Pinecone index name (required unless --dry-run)")
    ap.add_argument("--dry-run", action="store_true",
                    help="read, validate and build the records, check metadata limits, then stop — no network")
    ap.add_argument("--mode", choices=["full", "incremental"], default="full")
    ap.add_argument("--full-reembed", action="store_true", help="re-embed every record (model change)")
    ap.add_argument("--bedrock-region", default=os.environ.get("AWS_REGION", "us-east-1"))
    ap.add_argument("--pinecone-cloud", default="aws")
    ap.add_argument("--pinecone-region", default="us-east-1")
    ap.add_argument("--pinecone-secret-id", help="Secrets Manager id holding {\"api_key\": …}; else PINECONE_API_KEY")
    args = ap.parse_args()

    records, owned = records_from(args.workbooks)
    print(f"[1-3] {len(records)} records in {len(owned)} namespaces: {sorted(owned)}")
    if args.dry_run:
        for ns in sorted(owned):
            mine = [r for r in records if r.namespace == ns]
            live = [r for r in mine if r.action != "DELETE" and not r.exempt]
            for r in live:
                pinecone_metadata(r)                  # raises on anything Pinecone would reject
            biggest = max((len(json.dumps(pinecone_metadata(r))) for r in live), default=0)
            print(f"  {ns:13} would store {len(live):>4} | exempt {sum(r.exempt for r in mine):>2} | "
                  f"DELETE {sum(r.action == 'DELETE' for r in mine):>2} | largest metadata {biggest:,} bytes")
        print("dry run: nothing sent to Pinecone or Bedrock")
        return
    if not args.index:
        raise SystemExit("--index is required (or use --dry-run)")

    from pinecone import Pinecone
    key = os.environ.get("PINECONE_API_KEY")
    if args.pinecone_secret_id:
        import boto3
        key = json.loads(boto3.client("secretsmanager").get_secret_value(SecretId=args.pinecone_secret_id)["SecretString"])["api_key"]
    index = open_index(Pinecone(api_key=key), args.index, args.pinecone_cloud, args.pinecone_region)
    embed = titan_embedder(args.bedrock_region)

    print(f"[4-6] publishing ({args.mode}{', full re-embed' if args.full_reembed else ''})")
    stats = publish(index, embed, records, owned, args.mode, args.full_reembed)
    print(f"      embedded {stats['embedded']}, unchanged {stats['unchanged']}, deleted {stats['deleted']}, "
          f"exempt (not stored) {stats['exempt']}")
    print("[7] verify")
    sys.exit(0 if verify(index, embed, records, owned, stats["first"]) else 1)


if __name__ == "__main__":
    main()
