"""Create an RDS PostgreSQL instance reachable from your machine, and load the e-commerce data.

    your machine
        │  STEP 0  preflight: AWS identity, region, your public IP
        │  STEP 1  network: the account's default VPC
        │            ├─ DB subnet group   ecom-nlq-subnets   (the default VPC's subnets, ≥ 2 zones)
        │            └─ security group    ecom-nlq-db-sg     port 5432 from YOUR IP only (/32)
        │  STEP 2  instance ecom-nlq-db: PostgreSQL 16 · db.t4g.micro · 20 GB gp3 · encrypted ·
        │            publicly accessible · master password generated by RDS into Secrets Manager
        │  STEP 3  wait until available (a first create takes about 10 minutes)
        │  STEP 4  deployment.json: endpoint, port, database, secret ARN, security group
        │  STEP 5  load: load_postgres.py with that endpoint and secret — schema, data,
        ▼            comments, the 61 SQL examples
    RDS PostgreSQL  ecom-nlq-db.xxxx.<region>.rds.amazonaws.com:5432 / ecom

    cd ingestion
    python postgres/deploy.py                  create (or reuse), then load
    python postgres/deploy.py --skip-load      infrastructure only
    python postgres/deploy.py --destroy        delete instance, subnet group, security group

WHAT "PUBLICLY ACCESSIBLE" MEANS HERE
    The endpoint resolves to a public IP so your laptop can connect without a
    VPN. Who MAY connect is decided by the security group, which opens 5432 to
    your current IP only — never 0.0.0.0/0. Moved networks? Re-run deploy.py:
    it adds your new IP and keeps the old rules (remove those in the console).

WHERE THE PASSWORD LIVES
    RDS generates the master password and stores it in Secrets Manager
    (ManageMasterUserPassword). This script never sees, prints or writes it;
    load_postgres.py reads it from the secret at connect time. RDS rotates it
    every 7 days by default, which is why nothing should copy it.

SAFE TO RE-RUN
    Every step looks before it creates: an existing subnet group, security
    group, IP rule or instance is reused, not duplicated.

WHAT THIS DOES NOT DO
    - It does not create a VPC: it uses the account's default VPC, whose
      subnets are public. Without one it stops and says so.
    - It does not make a read-only user for the NLQ agent — the load uses the
      master user. Create a SELECT-only role before giving the agent access.
    - It does not change the size or engine of an instance that exists.
"""
import argparse
import json
import os
import ssl
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

import boto3
from botocore.exceptions import ClientError

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent                      # ingestion/ — data/ lives here
DEPLOYMENT = HERE / "deployment.json"
TAG = {"Key": "project", "Value": "ecom-nlq"}


def banner(text: str) -> None:
    print(f"\n=== {text} ===")


# ── STEP 0 — preflight ───────────────────────────────────────────────────
def ssl_context() -> ssl.SSLContext:
    """Certificates that verify on any machine.

    The python.org installer for macOS does not use the system keychain, so
    plain urllib fails with CERTIFICATE_VERIFY_FAILED until "Install
    Certificates.command" is run. certifi (installed with requests and httpx)
    carries Mozilla's bundle; botocore ships one too — that is why boto3 calls
    work on the same machine. Use whichever is present.
    """
    try:
        import certifi
        return ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        import botocore
        bundle = Path(botocore.__file__).parent / "cacert.pem"
        return ssl.create_default_context(cafile=str(bundle)) if bundle.exists() else ssl.create_default_context()


def my_public_ip() -> str:
    with urllib.request.urlopen("https://checkip.amazonaws.com", timeout=10, context=ssl_context()) as resp:
        return resp.read().decode().strip()


def preflight(session, cidr: str | None) -> str:
    banner("STEP 0: preflight")
    who = session.client("sts").get_caller_identity()
    print(f"  AWS      {who['Arn']}  region={session.region_name}")
    if not cidr:
        try:
            cidr = f"{my_public_ip()}/32"
        except OSError as exc:
            raise SystemExit(f"could not find your public IP ({exc})\n"
                             '  pass it yourself:  --allow-cidr "$(curl -s https://checkip.amazonaws.com)/32"')
    print(f"  access   port 5432 will be open to {cidr} only")
    return cidr


# ── STEP 1 — network ─────────────────────────────────────────────────────
def network(ec2, rds, prefix: str, cidr: str) -> tuple[str, str]:
    banner("STEP 1: network")
    vpcs = ec2.describe_vpcs(Filters=[{"Name": "is-default", "Values": ["true"]}])["Vpcs"]
    if not vpcs:
        raise SystemExit("this region has no default VPC — create one (`aws ec2 create-default-vpc`) "
                         "or extend this script to use your own public subnets")
    vpc_id = vpcs[0]["VpcId"]
    subnets = ec2.describe_subnets(Filters=[{"Name": "vpc-id", "Values": [vpc_id]}])["Subnets"]
    zones = {s["AvailabilityZone"] for s in subnets}
    if len(zones) < 2:
        raise SystemExit(f"default VPC {vpc_id} has subnets in {len(zones)} zone(s); RDS needs at least 2")
    print(f"  VPC      {vpc_id} (default) — {len(subnets)} subnets in {len(zones)} zones")

    group = f"{prefix}-subnets"
    try:
        rds.describe_db_subnet_groups(DBSubnetGroupName=group)
        print(f"  subnet group {group} exists")
    except ClientError as exc:
        if exc.response["Error"]["Code"] != "DBSubnetGroupNotFoundFault":
            raise
        rds.create_db_subnet_group(DBSubnetGroupName=group, DBSubnetGroupDescription="ecom NLQ database subnets",
                                   SubnetIds=[s["SubnetId"] for s in subnets], Tags=[TAG])
        print(f"  subnet group {group} created")

    sg_name = f"{prefix}-db-sg"
    found = ec2.describe_security_groups(Filters=[{"Name": "group-name", "Values": [sg_name]},
                                                  {"Name": "vpc-id", "Values": [vpc_id]}])["SecurityGroups"]
    if found:
        sg = found[0]
        print(f"  security group {sg_name} exists ({sg['GroupId']})")
    else:
        sg_id = ec2.create_security_group(GroupName=sg_name, Description="ecom NLQ Postgres - named IPs only",
                                          VpcId=vpc_id, TagSpecifications=[{"ResourceType": "security-group", "Tags": [TAG]}])["GroupId"]
        sg = ec2.describe_security_groups(GroupIds=[sg_id])["SecurityGroups"][0]
        print(f"  security group {sg_name} created ({sg_id})")
    allowed = {r["CidrIp"] for p in sg.get("IpPermissions", []) if p.get("FromPort") == 5432 for r in p.get("IpRanges", [])}
    if cidr in allowed:
        print(f"  5432 already open to {cidr}")
    else:
        ec2.authorize_security_group_ingress(GroupId=sg["GroupId"], IpPermissions=[{
            "IpProtocol": "tcp", "FromPort": 5432, "ToPort": 5432,
            "IpRanges": [{"CidrIp": cidr, "Description": "ecom-nlq deploy.py"}]}])
        print(f"  5432 opened to {cidr}")
    others = sorted(allowed - {cidr})
    if others:
        print(f"  also open to {others} (earlier runs) — remove in the console if no longer needed")
    return group, sg["GroupId"]


# ── STEP 2-3 — instance ──────────────────────────────────────────────────
def default_minor(rds, major: str) -> str:
    """The region's default PostgreSQL version for a major release, e.g. "16" -> "16.x"."""
    try:
        versions = rds.describe_db_engine_versions(Engine="postgres", EngineVersion=major, DefaultOnly=True)["DBEngineVersions"]
        return versions[0]["EngineVersion"] if versions else major
    except (ClientError, NotImplementedError):
        return major


def instance(rds, args, subnet_group: str, sg_id: str) -> dict:
    banner("STEP 2: instance")
    try:
        db = rds.describe_db_instances(DBInstanceIdentifier=args.instance)["DBInstances"][0]
        print(f"  {args.instance} exists — {db['Engine']} {db['EngineVersion']}, {db['DBInstanceClass']}, "
              f"status {db['DBInstanceStatus']}")
        if not db.get("PubliclyAccessible"):
            raise SystemExit(f"{args.instance} exists but is not publicly accessible — this script will not change it")
        if sg_id not in {g["VpcSecurityGroupId"] for g in db.get("VpcSecurityGroups", [])}:
            print(f"  note: {args.instance} does not use {sg_id}; your IP rule there will not apply")
    except ClientError as exc:
        if exc.response["Error"]["Code"] != "DBInstanceNotFound":
            raise
        version = args.engine_version if "." in args.engine_version else default_minor(rds, args.engine_version)
        print(f"  creating {args.instance}: postgres {version}, {args.instance_class}, {args.storage} GB gp3, publicly accessible")
        rds.create_db_instance(
            DBInstanceIdentifier=args.instance, Engine="postgres", EngineVersion=version,
            DBInstanceClass=args.instance_class, AllocatedStorage=args.storage, StorageType="gp3",
            StorageEncrypted=True, DBName=args.database, MasterUsername=args.master_user,
            ManageMasterUserPassword=True,                         # RDS generates it into Secrets Manager
            DBSubnetGroupName=subnet_group, VpcSecurityGroupIds=[sg_id], PubliclyAccessible=True,
            BackupRetentionPeriod=1, MultiAZ=False, AutoMinorVersionUpgrade=True,
            DeletionProtection=args.deletion_protection, Tags=[TAG])

    banner("STEP 3: wait until available")
    t0 = time.time()
    rds.get_waiter("db_instance_available").wait(DBInstanceIdentifier=args.instance,
                                                 WaiterConfig={"Delay": 20, "MaxAttempts": 90})
    db = rds.describe_db_instances(DBInstanceIdentifier=args.instance)["DBInstances"][0]
    print(f"  available after {time.time() - t0:.0f}s: {db['Endpoint']['Address']}:{db['Endpoint']['Port']}")
    if not db.get("MasterUserSecret"):
        raise SystemExit(f"{args.instance} has no RDS-managed secret — it was created with a fixed password; "
                         "set PG* in .env and run load_postgres.py directly")
    return db


# ── STEP 4-5 — record and load ───────────────────────────────────────────
def record(db, region: str, sg_id: str) -> dict:
    banner("STEP 4: deployment.json")
    info = {"instance": db["DBInstanceIdentifier"], "region": region,
            "host": db["Endpoint"]["Address"], "port": db["Endpoint"]["Port"], "database": db.get("DBName", "postgres"),
            "master_user": db["MasterUsername"], "secret_arn": db["MasterUserSecret"]["SecretArn"],
            "security_group": sg_id}
    DEPLOYMENT.write_text(json.dumps(info, indent=2) + "\n", encoding="utf-8")
    print(f"  wrote {DEPLOYMENT} (no password in it)")
    return info


def load(info: dict, args) -> None:
    banner("STEP 5: load")
    env = {**os.environ, "PGHOST": info["host"], "PGPORT": str(info["port"]), "PGDATABASE": info["database"],
           "PGSSLMODE": os.environ.get("PGSSLMODE", "require"), "AWS_REGION": info["region"],
           "AWS_DEFAULT_REGION": info["region"]}
    cmd = [sys.executable, str(HERE / "load_postgres.py"), "--data", str(args.data), "--secret-id", info["secret_arn"]]
    if args.kb_feed.exists():
        cmd += ["--kb-feed", str(args.kb_feed), "--check-examples"]
    else:
        print(f"  {args.kb_feed} not found — loading without comments and example checks")
    if subprocess.run(cmd, env=env).returncode != 0:
        raise SystemExit("load failed — the instance is up; fix the cause and re-run deploy.py (or with --skip-load to skip)")


# ── destroy ──────────────────────────────────────────────────────────────
def destroy(session, args) -> None:
    rds, ec2 = session.client("rds"), session.client("ec2")
    banner(f"DESTROY {args.instance}, {args.prefix}-subnets, {args.prefix}-db-sg")
    if not args.yes and input("  this deletes the database and all its data. type the instance name to confirm: ") != args.instance:
        raise SystemExit("  cancelled")
    try:
        rds.delete_db_instance(DBInstanceIdentifier=args.instance, SkipFinalSnapshot=True, DeleteAutomatedBackups=True)
        print("  deleting instance (several minutes)…")
        rds.get_waiter("db_instance_deleted").wait(DBInstanceIdentifier=args.instance, WaiterConfig={"Delay": 20, "MaxAttempts": 90})
        print("  instance deleted (its RDS-managed secret goes with it)")
    except ClientError as exc:
        if exc.response["Error"]["Code"] != "DBInstanceNotFound":
            raise
        print("  no instance")
    try:
        rds.delete_db_subnet_group(DBSubnetGroupName=f"{args.prefix}-subnets")
        print("  subnet group deleted")
    except ClientError as exc:
        if exc.response["Error"]["Code"] != "DBSubnetGroupNotFoundFault":
            raise
    for sg in ec2.describe_security_groups(Filters=[{"Name": "group-name", "Values": [f"{args.prefix}-db-sg"]}])["SecurityGroups"]:
        ec2.delete_security_group(GroupId=sg["GroupId"])
        print(f"  security group {sg['GroupId']} deleted")
    DEPLOYMENT.unlink(missing_ok=True)


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description="Create a publicly reachable RDS PostgreSQL and load the ecom data")
    ap.add_argument("--region", default=os.environ.get("AWS_REGION", "us-east-1"))
    ap.add_argument("--profile", default=os.environ.get("AWS_PROFILE"))
    ap.add_argument("--prefix", default="ecom-nlq", help="name prefix for the subnet group and security group")
    ap.add_argument("--instance", default=os.environ.get("RDS_INSTANCE", "ecom-nlq-db"))
    ap.add_argument("--database", default=os.environ.get("PGDATABASE_NAME", "ecom"))
    ap.add_argument("--master-user", default="ecom_admin")
    ap.add_argument("--instance-class", default=os.environ.get("RDS_INSTANCE_CLASS", "db.t4g.micro"))
    ap.add_argument("--storage", type=int, default=20, help="GB")
    ap.add_argument("--engine-version", default="16", help='"16" = the region\'s default 16.x')
    ap.add_argument("--deletion-protection", action="store_true")
    ap.add_argument("--allow-cidr", help="who may connect; default: your public IP /32")
    ap.add_argument("--data", type=Path, default=ROOT / "data" / "clean")
    ap.add_argument("--kb-feed", type=Path, default=ROOT / "data" / "kb_feed_ecom.xlsx")
    ap.add_argument("--skip-load", action="store_true")
    ap.add_argument("--destroy", action="store_true")
    ap.add_argument("--yes", action="store_true", help="with --destroy: do not ask")
    args = ap.parse_args(argv)

    session = boto3.Session(profile_name=args.profile, region_name=args.region)
    if args.destroy:
        destroy(session, args)
        return
    cidr = preflight(session, args.allow_cidr)
    rds, ec2 = session.client("rds"), session.client("ec2")
    subnet_group, sg_id = network(ec2, rds, args.prefix, cidr)
    db = instance(rds, args, subnet_group, sg_id)
    info = record(db, args.region, sg_id)
    if args.skip_load:
        print("\n--skip-load: infrastructure ready, nothing loaded")
    else:
        if not (args.data / "orders.csv").exists():
            raise SystemExit(f"{args.data} has no cleaned CSVs — run `python run.py prepare` first")
        load(info, args)
    # The FULL ARN: Secrets Manager adds a random 6-character suffix to every ARN
    # ("-bqiycw"), so the ARN's last segment is neither the secret's name nor
    # an id get-secret-value accepts.
    print(f"\ndone. psql: host={info['host']} port={info['port']} dbname={info['database']} user={info['master_user']}\n"
          f"password (rotates every 7 days — read it each time):\n"
          f"  aws secretsmanager get-secret-value --region {info['region']} "
          f"--secret-id '{info['secret_arn']}' --query SecretString --output text")


if __name__ == "__main__":
    main()
