"""Written knowledge for the e-commerce KB feed: what each table and column MEANS.

    TABLES   per table: title, domain, business description, grain, entities,
             measures, query guidance, synonyms, questions, type, source systems
    COLUMNS  per table: (column, role, description, synonyms, main_target)
             role decides where_to_use:  pk · fk · measure · enum · date · text · flag · geo · code · count

Measured facts (types, enum values, date formats, samples, decode maps) are
NOT written here — build_kb_feed.py measures them from the cleaned data.
"""

SCHEMA = "ecom"
DOMAIN = "E-commerce / Online Retail (US)"

TABLES = {
    "orders": dict(
        title="Orders", type="transactional", sources="web_store",
        description="Every order placed on the online store between 2023-01-01 and 2024-12-28: who ordered, when, how they paid, where it ships, how it was fulfilled, and the order's status. The header of an order — the products bought are in order_items.",
        grain="One row per order. order_id is unique.",
        entities="Order; customer; shipping destination; payment method; coupon; referral source; device.",
        measures="total_amount (merchandise subtotal — the amount paid); shipping_cost, tax_amount and discount_amount are stored beside it but NOT included in total_amount. Dimensions: order_status, payment_method, shipping_method, device_type, referral_source, coupon_code, is_gift, shipping_state.",
        guidance="Revenue = SUM(total_amount): merchandise only — say so. Money actually kept = orders whose payment status is Completed. For what was bought, join order_items. For where customers live use customers.state; orders.shipping_state is where the order went (they differ for 98% of orders).",
        synonyms="Orders; Sales Orders; Purchases; Transactions; Checkouts",
        questions="What is total revenue by month?; How many orders were placed last year?; What is the average order value by device?; Which states receive the most orders?; How many orders used a coupon?"),
    "order_items": dict(
        title="Order Items", type="transactional", sources="web_store",
        description="The product lines of each order: which product, how many, at what unit price. The only place that says WHAT was sold.",
        grain="One row per product line in an order (1-5 lines per order). order_item_id is unique.",
        entities="Order line; order; product.",
        measures="quantity (1-4); unit_price; total_price = quantity x unit_price. SUM(total_price) over an order = orders.total_amount.",
        guidance="Use for product, brand and category sales: join products on product_id (and categories for roll-ups). Units sold = SUM(quantity), not COUNT(*).",
        synonyms="Order Lines; Line Items; Basket Items; Products Sold",
        questions="What are the best-selling products by units?; What is revenue by category?; Which brands sell the most?; How many units of a product were sold?"),
    "payment_transactions": dict(
        title="Payment Transactions", type="transactional", sources="payment_gateway",
        description="The payment for each order: method, provider, amount, outcome, fees, fraud-risk signals (risk score, IP country, 3-D Secure) and chargebacks.",
        grain="One row per order's payment — exactly one per order (order_id is unique here).",
        entities="Payment; order; payment provider; card.",
        measures="amount (= orders.total_amount); processing_fee; risk_score (0-100). Dimensions: status, payment_method, payment_provider, ip_country, is_3d_secure, chargeback_raised.",
        guidance="status: Completed = money kept; Refunded = order returned OR cancelled; Failed = never charged. Chargeback and risk analysis start here.",
        synonyms="Payments; Transactions; Charges; Payment Records",
        questions="What share of payments failed?; How much was refunded?; What is the chargeback rate by payment method?; Which payments carry high risk scores?; What are total processing fees?"),
    "shipments": dict(
        title="Shipments", type="transactional", sources="fulfilment_system",
        description="Fulfilment of shipped orders: warehouse, carrier, tracking, ship and delivery dates, carrier cost, delivery time and on-time flag. Cancelled and Processing orders have none.",
        grain="One row per shipped order (order_id is unique here). Store Pickup orders also have one: the transfer of goods to the store.",
        entities="Shipment; order; warehouse; carrier.",
        measures="shipping_cost (the CARRIER's cost, 4-25 — not what the customer paid); weight_lbs; delivery_days_actual (0 when not delivered); on_time.",
        guidance="Average delivery time over status = 'Delivered' only. On-time rate = AVG(on_time) over delivered shipments.",
        synonyms="Shipments; Deliveries; Fulfilment; Parcels",
        questions="What is the on-time delivery rate by carrier?; What is the average delivery time by warehouse?; How many shipments are in transit?; Which carrier is cheapest per shipment?"),
    "customers": dict(
        title="Customers", type="dimension", sources="crm",
        description="Customer accounts: identity, home location, demographics (gender, birth year), segment, acquisition channel, loyalty points, lifetime orders and revenue, preferred device and newsletter status.",
        grain="One row per customer account. customer_id is unique.",
        entities="Customer; home address; segment; acquisition channel.",
        measures="loyalty_points; lifetime_orders (= COUNT of orders); lifetime_revenue (= SUM of orders.total_amount). Dimensions: customer_segment, acquisition_channel, gender, state, preferred_device.",
        guidance="Lifetime figures match the orders table; prefer computing from orders for any period other than 'all time'. Ages come from birth_year only.",
        synonyms="Customers; Shoppers; Buyers; Accounts; Users",
        questions="How many customers are in each segment?; Which acquisition channel brings the most revenue?; Who are the top customers by lifetime revenue?; How many customers subscribe to the newsletter?"),
    "customer_addresses": dict(
        title="Customer Addresses", type="dimension", sources="crm",
        description="Saved addresses of each customer, typed Shipping, Billing or Both, with exactly one default per customer.",
        grain="One row per saved address (1-2 per customer). address_id is unique.",
        entities="Address; customer.",
        measures="No measures. Dimensions: address_type, is_default, state.",
        guidance="A customer's default address: is_default = TRUE (exactly one). Orders do NOT reference these addresses — an order's shipping address is its own.",
        synonyms="Addresses; Saved Addresses; Address Book",
        questions="How many customers have more than one address?; What is a customer's default address?; How many addresses are billing-only?"),
    "products": dict(
        title="Products", type="dimension", sources="product_catalogue",
        description="The product catalogue: name, category, brand, price, cost, margin, stock, weight, rating, review count, return rate, featured and active flags, tags.",
        grain="One row per product (1,000). product_id and sku are unique; product_name is NOT unique.",
        entities="Product; brand; category.",
        measures="price; cost_price (= primary supplier's cost); margin_pct; stock_quantity (= inventory available across warehouses); avg_rating; review_count; return_rate_pct (percent).",
        guidance="Identify products by product_id or sku. Names are adjective + category ('Smart Running Shoes'). For category roll-ups join categories on category_id and walk parent_category_id.",
        synonyms="Products; Catalogue; Items; SKUs; Merchandise",
        questions="Which products have the highest margin?; What is the average price by brand?; Which products are low on stock?; Which products are returned most?; How many products are active?"),
    "categories": dict(
        title="Categories", type="dimension", sources="product_catalogue",
        description="The category hierarchy: 10 top-level categories, their sub-categories, and sub-sub-categories.",
        grain="One row per category. category_id is unique. Levels 1-3.",
        entities="Category; parent category.",
        measures="No measures. category_level 1-3.",
        guidance="Products sit at level 2 or 3. To roll up to the top level, join categories to itself on parent_category_id (twice for level 3).",
        synonyms="Categories; Product Categories; Departments; Category Tree",
        questions="What are the top-level categories?; Which sub-categories sit under Electronics?; What is revenue by top-level category?"),
    "inventory": dict(
        title="Inventory", type="snapshot", sources="warehouse_management",
        description="Stock of each product in each warehouse: available and reserved units, reorder point, last restock, last stock check, bin location.",
        grain="One row per product per warehouse (product_id + warehouse_id is unique).",
        entities="Stock position; product; warehouse; bin.",
        measures="quantity_available (free-to-sell); quantity_reserved (held for open orders, in ADDITION to available); reorder_point.",
        guidance="On hand = available + reserved. Below reorder point = quantity_available < reorder_point.",
        synonyms="Inventory; Stock; Stock Levels; On Hand",
        questions="Which products are below their reorder point?; How much stock does each warehouse hold?; Which products are out of stock?"),
    "warehouses": dict(
        title="Warehouses", type="dimension", sources="warehouse_management",
        description="The 5 US distribution centres: location, capacity, manager, opening date.",
        grain="One row per warehouse (5).",
        entities="Warehouse.",
        measures="capacity_sqft.",
        guidance="Join inventory and shipments on warehouse_id.",
        synonyms="Warehouses; Distribution Centres; DCs; Fulfilment Centres; Hubs",
        questions="Which warehouse ships the most orders?; Where are the warehouses?; Which warehouse has the largest capacity?"),
    "suppliers": dict(
        title="Suppliers", type="dimension", sources="procurement",
        description="Suppliers of products: company, contact, location, country, payment terms and rating.",
        grain="One row per supplier (150).",
        entities="Supplier.",
        measures="rating (1-5). Dimensions: country, payment_terms.",
        guidance="Which products a supplier provides: product_suppliers.",
        synonyms="Suppliers; Vendors; Manufacturers; Sources",
        questions="Which countries do suppliers come from?; Which suppliers have the best rating?; Which suppliers use Net 30 terms?"),
    "product_suppliers": dict(
        title="Product Suppliers", type="bridge", sources="procurement",
        description="Which supplier can supply which product, at what cost, lead time and minimum order quantity. Exactly one primary supplier per product.",
        grain="One row per product per supplier.",
        entities="Supply agreement; product; supplier.",
        measures="cost_price; lead_time_days; minimum_order_quantity.",
        guidance="The primary supplier's cost_price is products.cost_price. Filter is_primary_supplier = TRUE for one supplier per product.",
        synonyms="Product Suppliers; Supply Agreements; Sourcing; Vendor Catalogue",
        questions="Who is the primary supplier of a product?; Which products have more than one supplier?; What is the average lead time by supplier country?"),
    "promotions": dict(
        title="Promotions", type="dimension", sources="marketing",
        description="Promotions: the 10 coupon codes used in orders (promotion_id 12101-12110) and 100 catalogue promotions that no order references.",
        grain="One row per promotion. promo_code is unique.",
        entities="Promotion; coupon code.",
        measures="discount_percent; discount_amount; min_purchase_amount; max_discount; usage_limit; times_used.",
        guidance="Join orders.coupon_code = promotions.promo_code. Only the coupon promotions have orders; catalogue promotions' times_used is the promotion system's own counter. Status is as of 2024-12-31.",
        synonyms="Promotions; Coupons; Discounts; Offers; Promo Codes",
        questions="Which coupon drives the most revenue?; How many orders used each coupon?; Which promotions are active?; What discount does each coupon give?"),
    "reviews": dict(
        title="Reviews", type="transactional", sources="web_store",
        description="Product reviews by customers who bought the product: rating, title, text, sentiment, helpful votes, seller response, images.",
        grain="One row per review. review_id is unique.",
        entities="Review; product; customer.",
        measures="rating (1-5); helpful_votes. Dimensions: sentiment, seller_responded, contains_image.",
        guidance="sentiment follows rating exactly: 1-2 Negative, 3 Neutral, 4-5 Positive. Every reviewer bought the product.",
        synonyms="Reviews; Ratings; Feedback; Product Reviews",
        questions="Which products have the lowest ratings?; What share of reviews are negative?; Do reviews with images get more helpful votes?"),
}

# (column, role, description, synonyms, main_investigative_target)
C = {}
C["orders"] = [
    ("order_id", "pk", "Unique order identifier (3001-53000). Joins order_items, payment_transactions and shipments.", "Order ID; Order Number; Order #", "Y"),
    ("customer_id", "fk", "The customer who placed the order. Joins customers.customer_id.", "Customer ID; Buyer ID", "Y"),
    ("order_date", "date", "When the order was placed (2023-01-01 to 2024-12-28).", "Order Date; Purchase Date; Placed At", "Y"),
    ("total_amount", "measure", "Merchandise subtotal = SUM(order_items.total_price); the amount paid. Shipping, tax and discount are NOT included.", "Order Total; Order Value; Revenue; Sales; Subtotal", "Y"),
    ("payment_method", "enum", "How the customer paid.", "Payment Method; Payment Type; Paid With", "N"),
    ("order_status", "enum", "Delivered, Shipped (in transit), Returned (refunded), Processing (not shipped yet) or Cancelled (failed or refunded payment).", "Order Status; Status; State of Order", "Y"),
    ("shipping_address", "text", "Street address the order shipped to — this order's own destination, not the customer's address.", "Shipping Address; Delivery Address; Ship-To Address", "N"),
    ("shipping_city", "text", "City the order shipped to.", "Shipping City; Delivery City", "N"),
    ("shipping_state", "geo", "US state or territory code the order shipped to.", "Shipping State; Delivery State; Destination State", "N"),
    ("shipping_zip", "code", "5-digit ZIP the order shipped to; text, keep leading zeros.", "Shipping ZIP; Delivery ZIP; Postal Code", "N"),
    ("device_type", "enum", "Device the order was placed from.", "Device; Device Type; Platform", "N"),
    ("shipping_method", "enum", "Delivery option chosen at checkout.", "Shipping Method; Delivery Option; Shipping Speed", "N"),
    ("shipping_cost", "measure", "Shipping CHARGED TO THE CUSTOMER (mostly 0; 0 for FREESHIP and Store Pickup). Not in total_amount. The carrier's cost is shipments.shipping_cost.", "Shipping Charge; Shipping Fee; Delivery Charge", "N"),
    ("tax_amount", "measure", "Sales tax on the order. Not in total_amount.", "Tax; Sales Tax; Tax Amount", "N"),
    ("discount_amount", "measure", "Coupon discount = coupon rate x total_amount (SAVE10 = 10%); 0 without a coupon. Informational: not subtracted from total_amount.", "Discount; Coupon Discount; Savings", "N"),
    ("coupon_code", "enum", "Coupon used; empty when none. Joins promotions.promo_code.", "Coupon; Coupon Code; Promo Code; Voucher", "N"),
    ("referral_source", "enum", "Marketing source that referred the order.", "Referral Source; Traffic Source; Channel", "N"),
    ("estimated_delivery_date", "date", "Delivery date promised at checkout.", "Estimated Delivery; Promised Date; ETA", "N"),
    ("is_gift", "flag", "TRUE when the order was marked as a gift.", "Gift Order; Is Gift", "N"),
]
C["order_items"] = [
    ("order_item_id", "pk", "Unique order-line identifier.", "Order Item ID; Line ID", "N"),
    ("order_id", "fk", "The order this line belongs to. Joins orders.order_id.", "Order ID; Order Number", "Y"),
    ("product_id", "fk", "The product sold on this line. Joins products.product_id.", "Product ID; Item ID", "Y"),
    ("quantity", "measure", "Units of the product on this line (1-4). Units sold = SUM(quantity).", "Quantity; Units; Qty; Units Sold", "Y"),
    ("unit_price", "measure", "Price per unit at the time of sale.", "Unit Price; Price Paid; Selling Price", "N"),
    ("total_price", "measure", "Line value = quantity x unit_price. Sums to orders.total_amount per order.", "Line Total; Line Revenue; Sales Amount", "Y"),
]
C["payment_transactions"] = [
    ("transaction_id", "pk", "Unique payment identifier.", "Transaction ID; Payment ID", "N"),
    ("order_id", "fk", "The order paid for — exactly one payment per order. Joins orders.order_id.", "Order ID", "Y"),
    ("payment_method", "enum", "How the customer paid (same as orders.payment_method).", "Payment Method; Payment Type", "N"),
    ("payment_provider", "enum", "Company that processed the payment.", "Payment Provider; Processor; Gateway", "N"),
    ("transaction_date", "date", "When the payment was taken (= order_date).", "Transaction Date; Payment Date; Charged At", "N"),
    ("amount", "measure", "Amount charged = orders.total_amount (merchandise subtotal).", "Amount; Payment Amount; Charged Amount", "Y"),
    ("currency", "enum", "Currency of the payment (all USD).", "Currency", "N"),
    ("status", "enum", "Completed = money kept; Refunded = order returned OR cancelled; Failed = never charged.", "Payment Status; Transaction Status", "Y"),
    ("card_last_four", "code", "Last four card digits; 4-digit text; empty for non-card methods.", "Card Last Four; Last 4; Card Number Ending", "N"),
    ("authorization_code", "code", "Processor's authorisation reference.", "Authorization Code; Auth Code; Approval Code", "N"),
    ("processing_fee", "measure", "Fee charged by the payment provider.", "Processing Fee; Transaction Fee; Payment Fee", "N"),
    ("risk_score", "measure", "Fraud-risk score from the gateway (0-100, higher = riskier).", "Risk Score; Fraud Score; Risk", "Y"),
    ("ip_country", "geo", "Country of the buyer's IP address (ISO-2 code).", "IP Country; Buyer Country; Location", "N"),
    ("is_3d_secure", "flag", "TRUE when the card payment passed 3-D Secure authentication.", "3D Secure; 3DS; Strong Authentication", "N"),
    ("chargeback_raised", "flag", "TRUE when the cardholder disputed the payment.", "Chargeback; Dispute; Chargeback Raised", "Y"),
]
C["shipments"] = [
    ("shipment_id", "pk", "Unique shipment identifier.", "Shipment ID", "N"),
    ("order_id", "fk", "The order shipped. Joins orders.order_id (one shipment per shipped order).", "Order ID", "Y"),
    ("warehouse_id", "fk", "Warehouse it shipped from. Joins warehouses.warehouse_id.", "Warehouse ID; Origin Warehouse", "Y"),
    ("carrier", "enum", "Delivery company.", "Carrier; Courier; Shipping Company", "Y"),
    ("tracking_number", "code", "Carrier tracking number.", "Tracking Number; Tracking ID; AWB", "N"),
    ("ship_date", "date", "When it left the warehouse.", "Ship Date; Dispatch Date; Shipped At", "N"),
    ("estimated_delivery", "date", "Carrier's promised delivery time.", "Estimated Delivery; ETA; Expected Delivery", "N"),
    ("actual_delivery", "date", "When it was delivered; empty while In Transit or Returned.", "Actual Delivery; Delivered At; Delivery Date", "N"),
    ("shipping_cost", "measure", "The CARRIER's cost for the shipment (4-25) — not what the customer paid (orders.shipping_cost).", "Carrier Cost; Freight Cost; Shipping Cost", "N"),
    ("weight_lbs", "measure", "Shipment weight in pounds.", "Weight; Package Weight; Weight lbs", "N"),
    ("status", "enum", "Delivered, In Transit or Returned.", "Shipment Status; Delivery Status", "Y"),
    ("origin_lat", "geo", "Latitude of the origin warehouse.", "Origin Latitude", "N"),
    ("origin_lon", "geo", "Longitude of the origin warehouse.", "Origin Longitude", "N"),
    ("destination_lat", "geo", "Latitude of the delivery address.", "Destination Latitude", "N"),
    ("destination_lon", "geo", "Longitude of the delivery address.", "Destination Longitude", "N"),
    ("delivery_days_actual", "measure", "Days from ship_date to actual_delivery; 0 when not delivered — average over Delivered only.", "Delivery Days; Transit Time; Days to Deliver", "Y"),
    ("on_time", "flag", "TRUE when delivered by the estimated delivery time; FALSE for non-delivered.", "On Time; Delivered On Time; OTD", "Y"),
]
C["customers"] = [
    ("customer_id", "pk", "Unique customer identifier (1001-11000).", "Customer ID; Customer Number; Account ID", "Y"),
    ("first_name", "text", "Customer's first name.", "First Name; Given Name", "N"),
    ("last_name", "text", "Customer's last name.", "Last Name; Surname; Family Name", "N"),
    ("email", "text", "Customer's email address (unique).", "Email; Email Address", "N"),
    ("phone", "text", "Customer's phone number.", "Phone; Phone Number; Mobile", "N"),
    ("address", "text", "Street of the customer's home address.", "Address; Home Address; Street", "N"),
    ("city", "text", "City of the home address.", "City; Home City", "N"),
    ("state", "geo", "US state or territory code of the home address.", "State; Home State; Customer State", "Y"),
    ("zip_code", "code", "5-digit home ZIP; text, keep leading zeros.", "ZIP; ZIP Code; Postal Code", "N"),
    ("country", "enum", "Country (all USA).", "Country", "N"),
    ("created_at", "date", "Account creation — never after the customer's first order or address.", "Created At; Signup Date; Joined; Registration Date", "Y"),
    ("lat", "geo", "Latitude of the home address.", "Latitude", "N"),
    ("lon", "geo", "Longitude of the home address.", "Longitude", "N"),
    ("gender", "enum", "Gender as recorded.", "Gender; Sex", "N"),
    ("birth_year", "measure", "Year of birth (1954-2006); age = reference year - birth_year.", "Birth Year; Year of Birth; Age", "N"),
    ("customer_segment", "enum", "Marketing segment.", "Segment; Customer Segment; Tier", "Y"),
    ("acquisition_channel", "enum", "Channel through which the customer signed up.", "Acquisition Channel; Signup Channel; Source", "Y"),
    ("loyalty_points", "measure", "Current loyalty points balance.", "Loyalty Points; Points; Rewards", "N"),
    ("lifetime_orders", "count", "Number of orders ever placed (= COUNT of orders).", "Lifetime Orders; Order Count; Total Orders", "N"),
    ("lifetime_revenue", "measure", "Total merchandise value ever ordered (= SUM of orders.total_amount).", "Lifetime Revenue; Lifetime Value; LTV; CLV", "Y"),
    ("last_order_date", "date", "Most recent order; empty for the 56 customers with no orders.", "Last Order Date; Last Purchase; Most Recent Order", "N"),
    ("preferred_device", "enum", "Device the customer uses most.", "Preferred Device; Main Device", "N"),
    ("is_newsletter_subscribed", "flag", "TRUE when subscribed to the newsletter.", "Newsletter; Subscribed; Email Opt-In", "N"),
]
C["customer_addresses"] = [
    ("address_id", "pk", "Unique address identifier.", "Address ID", "N"),
    ("customer_id", "fk", "Owner of the address. Joins customers.customer_id.", "Customer ID", "Y"),
    ("address_type", "enum", "Shipping, Billing, or Both.", "Address Type; Address Use", "N"),
    ("is_default", "flag", "TRUE for the customer's default address — exactly one per customer.", "Default Address; Primary Address; Is Default", "N"),
    ("address_line1", "text", "Street line 1.", "Address Line 1; Street", "N"),
    ("address_line2", "text", "Apartment or suite; often empty.", "Address Line 2; Apartment; Suite", "N"),
    ("city", "text", "City.", "City", "N"),
    ("state", "geo", "US state or territory code.", "State", "N"),
    ("zip_code", "code", "5-digit ZIP; text, keep leading zeros.", "ZIP; ZIP Code", "N"),
    ("country", "enum", "Country (all USA).", "Country", "N"),
    ("phone", "text", "Phone number for this address.", "Phone", "N"),
    ("created_at", "date", "When the address was saved.", "Created At; Added On", "N"),
]
C["products"] = [
    ("product_id", "pk", "Unique product identifier (2001-3000).", "Product ID; Item ID", "Y"),
    ("product_name", "text", "Adjective + category ('Smart Running Shoes'); NOT unique.", "Product Name; Item Name; Product", "Y"),
    ("category_id", "fk", "The product's category (level 2 or 3). Joins categories.category_id.", "Category ID", "N"),
    ("category", "enum", "Category name (level 2 or 3); prefer category_id for joins.", "Category; Product Category; Sub-category", "Y"),
    ("brand", "enum", "Brand of the product.", "Brand; Make; Manufacturer Brand", "Y"),
    ("price", "measure", "Current list price.", "Price; List Price; Selling Price", "Y"),
    ("stock_quantity", "measure", "Free-to-sell units across all warehouses (= SUM of inventory.quantity_available).", "Stock; Stock Quantity; Units in Stock", "N"),
    ("description", "text", "Adjective, category and brand, with the category path.", "Description; Product Description", "N"),
    ("created_at", "date", "When the product was added to the catalogue.", "Created At; Added On; Launch Date", "N"),
    ("sku", "code", "Stock-keeping unit (unique), e.g. NIK-RUN-1000.", "SKU; Item Code; Product Code", "N"),
    ("weight_kg", "measure", "Product weight in kilograms.", "Weight; Weight kg", "N"),
    ("cost_price", "measure", "Unit cost = the primary supplier's cost_price.", "Cost; Unit Cost; Cost Price; COGS", "N"),
    ("margin_pct", "measure", "Gross margin percent = (price - cost_price) / price x 100.", "Margin; Margin %; Gross Margin", "Y"),
    ("avg_rating", "measure", "Mean review rating (1-5).", "Rating; Average Rating; Stars", "Y"),
    ("review_count", "count", "Number of reviews (= COUNT of reviews).", "Review Count; Number of Reviews", "N"),
    ("return_rate_pct", "measure", "PERCENT (0-100) of the product's shipped order lines whose order was Returned.", "Return Rate; Returns %; Return Percentage", "Y"),
    ("is_featured", "flag", "TRUE when featured on the store front.", "Featured; Is Featured", "N"),
    ("is_active", "flag", "TRUE when currently for sale.", "Active; Is Active; Available for Sale", "N"),
    ("tags", "text", "Comma-separated tags, e.g. 'new-arrival, eco-friendly'; use LIKE '%tag%'.", "Tags; Labels; Attributes", "N"),
]
C["categories"] = [
    ("category_id", "pk", "Unique category identifier.", "Category ID", "N"),
    ("category_name", "enum", "Category name.", "Category; Category Name", "Y"),
    ("parent_category_id", "fk", "Parent category; empty for the 10 top-level categories. Joins categories.category_id.", "Parent Category; Parent ID", "N"),
    ("category_level", "enum", "1 = top level, 2 = sub-category, 3 = sub-sub-category.", "Level; Category Level; Depth", "N"),
    ("description", "text", "Short description of the category.", "Description", "N"),
    ("created_at", "date", "When the category was created (all 2023-01-01).", "Created At", "N"),
]
C["inventory"] = [
    ("inventory_id", "pk", "Unique stock-position identifier.", "Inventory ID", "N"),
    ("product_id", "fk", "The product. Joins products.product_id.", "Product ID", "Y"),
    ("warehouse_id", "fk", "The warehouse. Joins warehouses.warehouse_id.", "Warehouse ID", "Y"),
    ("quantity_available", "measure", "Free-to-sell units; reserved units are NOT included.", "Available; Available Stock; Free Stock; On Shelf", "Y"),
    ("quantity_reserved", "measure", "Units held for open orders, in addition to available. On hand = available + reserved.", "Reserved; Allocated; Held", "N"),
    ("reorder_point", "measure", "Level at which to reorder; below it when quantity_available < reorder_point.", "Reorder Point; Reorder Level; Minimum Stock", "N"),
    ("last_restock_date", "date", "When stock was last replenished.", "Last Restock; Last Replenishment", "N"),
    ("last_stock_check", "date", "When stock was last counted.", "Last Stock Check; Last Count; Cycle Count Date", "N"),
    ("bin_location", "code", "Aisle-shelf-bin location in the warehouse.", "Bin; Bin Location; Shelf Location", "N"),
]
C["warehouses"] = [
    ("warehouse_id", "pk", "Unique warehouse identifier (1-5).", "Warehouse ID", "Y"),
    ("warehouse_name", "enum", "Warehouse name.", "Warehouse; Warehouse Name; DC Name", "Y"),
    ("address", "text", "Street address.", "Address", "N"),
    ("city", "enum", "City.", "City", "N"),
    ("state", "geo", "State code.", "State", "N"),
    ("zip_code", "code", "5-digit ZIP; text.", "ZIP", "N"),
    ("country", "enum", "Country (all USA).", "Country", "N"),
    ("phone", "text", "Phone number.", "Phone", "N"),
    ("email", "text", "Email address.", "Email", "N"),
    ("capacity_sqft", "measure", "Floor capacity in square feet.", "Capacity; Size; Square Feet", "N"),
    ("manager_name", "text", "Warehouse manager.", "Manager; Warehouse Manager", "N"),
    ("operating_since", "date", "Opening date.", "Operating Since; Opened", "N"),
    ("lat", "geo", "Latitude.", "Latitude", "N"),
    ("lon", "geo", "Longitude.", "Longitude", "N"),
]
C["suppliers"] = [
    ("supplier_id", "pk", "Unique supplier identifier (10001-10150).", "Supplier ID; Vendor ID", "Y"),
    ("supplier_name", "text", "Company name.", "Supplier; Supplier Name; Vendor Name", "Y"),
    ("contact_person", "text", "Main contact.", "Contact; Contact Person", "N"),
    ("email", "text", "Contact email.", "Email", "N"),
    ("phone", "text", "Contact phone.", "Phone", "N"),
    ("address", "text", "Street address.", "Address", "N"),
    ("city", "text", "City.", "City", "N"),
    ("state", "text", "State or province.", "State; Province", "N"),
    ("country", "enum", "Country.", "Country; Supplier Country", "Y"),
    ("payment_terms", "enum", "Payment terms agreed with the supplier (see glossary).", "Payment Terms; Terms", "N"),
    ("rating", "measure", "Supplier rating (1-5).", "Rating; Supplier Rating; Score", "Y"),
    ("created_at", "date", "When the supplier was onboarded.", "Created At; Onboarded", "N"),
]
C["product_suppliers"] = [
    ("product_supplier_id", "pk", "Unique supply-agreement identifier.", "Product Supplier ID", "N"),
    ("product_id", "fk", "The product. Joins products.product_id.", "Product ID", "Y"),
    ("supplier_id", "fk", "The supplier. Joins suppliers.supplier_id.", "Supplier ID", "Y"),
    ("cost_price", "measure", "This supplier's unit cost for the product.", "Cost; Supplier Cost; Unit Cost", "Y"),
    ("lead_time_days", "measure", "Days from purchase order to delivery.", "Lead Time; Lead Time Days", "N"),
    ("minimum_order_quantity", "measure", "Minimum units per purchase order.", "MOQ; Minimum Order Quantity", "N"),
    ("is_primary_supplier", "flag", "TRUE for the product's primary supplier — exactly one per product.", "Primary Supplier; Is Primary; Main Supplier", "Y"),
    ("last_order_date", "date", "When the product was last ordered from this supplier.", "Last Order Date; Last PO", "N"),
]
C["promotions"] = [
    ("promotion_id", "pk", "Unique promotion identifier; 12101-12110 are the coupons used in orders.", "Promotion ID", "N"),
    ("promotion_name", "text", "Promotion name, e.g. 'Coupon SAVE10'.", "Promotion; Promotion Name; Campaign", "Y"),
    ("promotion_type", "enum", "Percentage, Fixed Amount, Buy One Get One, or Free Shipping.", "Promotion Type; Discount Type", "N"),
    ("discount_percent", "measure", "Percent off, for Percentage promotions.", "Discount %; Percent Off", "N"),
    ("discount_amount", "measure", "Amount off, for Fixed Amount promotions.", "Discount Amount; Amount Off", "N"),
    ("start_date", "date", "Start; for coupons, the first order that used the code.", "Start Date; Starts", "N"),
    ("end_date", "date", "End; empty for coupons (no end date known).", "End Date; Ends; Expiry", "N"),
    ("promo_code", "code", "Unique code; coupons match orders.coupon_code.", "Promo Code; Coupon Code; Code", "Y"),
    ("min_purchase_amount", "measure", "Minimum basket value to qualify.", "Minimum Purchase; Minimum Spend", "N"),
    ("max_discount", "measure", "Cap on the discount.", "Maximum Discount; Discount Cap", "N"),
    ("status", "enum", "As of 2024-12-31: Active, Expired or Scheduled.", "Promotion Status; Status", "N"),
    ("usage_limit", "measure", "Maximum redemptions allowed; empty = unlimited.", "Usage Limit; Max Uses", "N"),
    ("times_used", "count", "Redemptions: for coupons, COUNT of orders using the code; for catalogue promotions, the system's own counter.", "Times Used; Redemptions; Uses", "N"),
]
C["reviews"] = [
    ("review_id", "pk", "Unique review identifier.", "Review ID", "N"),
    ("product_id", "fk", "The product reviewed. Joins products.product_id.", "Product ID", "Y"),
    ("customer_id", "fk", "The reviewer. Joins customers.customer_id.", "Customer ID; Reviewer", "N"),
    ("rating", "measure", "Stars, 1-5.", "Rating; Stars; Score", "Y"),
    ("review_title", "text", "Review headline.", "Review Title; Headline", "N"),
    ("review_text", "text", "Review body.", "Review Text; Comment; Review", "N"),
    ("review_date", "date", "When the review was written (always after the purchase).", "Review Date; Reviewed On", "N"),
    ("verified_purchase", "flag", "TRUE when the reviewer bought the product (all reviews).", "Verified Purchase; Verified Buyer", "N"),
    ("helpful_votes", "measure", "Number of 'helpful' votes.", "Helpful Votes; Upvotes", "N"),
    ("sentiment", "enum", "Negative (1-2 stars), Neutral (3), Positive (4-5).", "Sentiment; Tone", "Y"),
    ("seller_responded", "flag", "TRUE when the seller replied.", "Seller Responded; Seller Reply", "N"),
    ("contains_image", "flag", "TRUE when the review includes a photo.", "Has Image; Photo Review", "N"),
]

WHERE_TO_USE = {
    "pk": "WHERE (entity lookup); JOIN key; COUNT(DISTINCT)",
    "fk": "JOIN key; WHERE (filter to one entity); GROUP BY",
    "measure": "SELECT / aggregate (SUM, AVG, MIN, MAX); WHERE / HAVING (thresholds); ORDER BY",
    "count": "SELECT; WHERE / HAVING (thresholds); ORDER BY — prefer computing from the source table for a period",
    "enum": "WHERE (equality, IN); GROUP BY; SELECT for display",
    "date": "WHERE (date range); GROUP BY date_trunc('month', …); ORDER BY",
    "text": "SELECT (display); WHERE (LIKE / exact match)",
    "flag": "WHERE (= TRUE / = FALSE); AVG(CAST(… AS INT)) for rates; GROUP BY",
    "geo": "WHERE (equality, IN); GROUP BY; SELECT for display",
    "code": "WHERE (exact match — compare as text); SELECT for display",
}

JOINS = [
    ("orders", "customers", "customer_id", "many-to-one", "Each order belongs to one customer; a customer has many orders (56 customers have none)."),
    ("order_items", "orders", "order_id", "many-to-one", "1-5 product lines per order; SUM(order_items.total_price) = orders.total_amount."),
    ("order_items", "products", "product_id", "many-to-one", "What was sold: join for product, brand and category sales."),
    ("payment_transactions", "orders", "order_id", "one-to-one", "Exactly one payment per order; amount = orders.total_amount."),
    ("shipments", "orders", "order_id", "one-to-one", "One shipment per shipped order; Cancelled and Processing orders have none — use LEFT JOIN from orders."),
    ("shipments", "warehouses", "warehouse_id", "many-to-one", "Warehouse a shipment left from."),
    ("customer_addresses", "customers", "customer_id", "many-to-one", "1-2 saved addresses per customer; exactly one is_default = TRUE."),
    ("reviews", "products", "product_id", "many-to-one", "Reviews of a product; COUNT = products.review_count, AVG(rating) = products.avg_rating."),
    ("reviews", "customers", "customer_id", "many-to-one", "The reviewer, who always bought the product."),
    ("products", "categories", "category_id", "many-to-one", "The product's level 2 or 3 category."),
    ("categories", "categories", "parent_category_id = category_id", "many-to-one", "Category hierarchy: self-join for parent; twice to reach level 1 from level 3."),
    ("inventory", "products", "product_id", "many-to-one", "Stock of a product per warehouse; SUM(quantity_available) = products.stock_quantity."),
    ("inventory", "warehouses", "warehouse_id", "many-to-one", "Stock held in a warehouse."),
    ("product_suppliers", "products", "product_id", "many-to-one", "Suppliers of a product; is_primary_supplier = TRUE for exactly one."),
    ("product_suppliers", "suppliers", "supplier_id", "many-to-one", "Products a supplier provides."),
    ("orders", "promotions", "coupon_code = promo_code", "many-to-one", "Coupon used by an order; only promotions 12101-12110 have orders. Use LEFT JOIN: most orders have no coupon."),
]

STATE_NAMES = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas", "CA": "California", "CO": "Colorado",
    "CT": "Connecticut", "DE": "Delaware", "FL": "Florida", "GA": "Georgia", "HI": "Hawaii", "ID": "Idaho",
    "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana",
    "ME": "Maine", "MD": "Maryland", "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
    "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey",
    "NM": "New Mexico", "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma",
    "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina", "SD": "South Dakota",
    "TN": "Tennessee", "TX": "Texas", "UT": "Utah", "VT": "Vermont", "VA": "Virginia", "WA": "Washington",
    "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming", "DC": "District of Columbia", "PR": "Puerto Rico",
    "GU": "Guam", "VI": "U.S. Virgin Islands", "AS": "American Samoa", "MP": "Northern Mariana Islands",
    "FM": "Federated States of Micronesia", "MH": "Marshall Islands", "PW": "Palau"}
COUNTRY_NAMES = {"US": "United States", "GB": "United Kingdom", "MX": "Mexico", "CA": "Canada", "DE": "Germany",
                 "FR": "France", "IN": "India", "CN": "China", "BR": "Brazil", "AU": "Australia", "JP": "Japan",
                 "NG": "Nigeria", "RU": "Russia"}
